---
# tasks file for cloudwatch-agent-install
- name: Ping servers
  ping:

- name: Install CloudWatch agent
  apt:
    deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

- name: Create CloudWatch agent configuration
  copy:
    dest: "{{ configurationPath }}"
    content: |
      {
        "metrics":{
            "metrics_collected":{
              "mem":{
                  "measurement":[
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval":60
              }
            },
            "append_dimensions": {
              "InstanceId": "${aws:InstanceId}"
            }
        }
      }
  notify: 
    - ReloadCW
    - GetStatus
    
- name: Status Cloudwatch agent 2
  service: 
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes

