creation_rules:
  - path_regex: environments(/|\\)eu-central-1(/|\\)dev(/|\\)secrets(/|\\).*\.yaml(\.unencrypted)?$
    hc_vault_transit_uri: "https://vault-url/v1/<namespace>/sops/keys/first-dev"
  - path_regex: environments(/|\\)eu-central-1(/|\\)prod(/|\\)secrets(/|\\).*\.yaml(\.unencrypted)?$
    hc_vault_transit_uri: "https://vault-url/v1/<namespace>/sops/keys/first-prod"