---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: my-email@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "syncsoul.org"
      dns01:
        route53:
          region: eu-central-1
          accessKeyID: AKIxxxxxx
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key