---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v1-client
  template:
    metadata:
      labels:
        labels:
        app: client
        version: v1-client
        istio: monitor
        # sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: client
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: backend
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: client
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: client
  namespace: backend
spec:
  host: client
  subsets:
    - name: v1-client
      labels:
        app: client
        version: v1-client
    # - name: v2
    #   labels:
    #     app: client
    #     version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: client
  namespace: backend
spec:
  hosts:
    - client
    # - client-1.home-k8s.lab # if ingress used (ingress nginx, for example)
  http:
    - route:
        - destination:
            host: client
            subset: v1-client
          weight: 100
        # - destination:
        #     host: client
        #     subset: v2
        #   weight: 100
